spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
server:
  port: 8913
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
